name: Telegram Bot Workflow

on:
  schedule:
    - cron: '*/32 * * * *'  # Menjalankan setiap 32 menit
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    # Tambahkan konfigurasi concurrency untuk mencegah duplikasi job
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run Telegram Bot
        env:
          TELEGRAM_BOT_API: ${{ secrets.TELEGRAM_BOT_API }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python bot.py
