name: Telegram Bot Workflow

on:
  schedule:
    - cron: '*/1 * * * *'  # Setiap menit
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Python 3.10
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run Telegram Bot
      - name: Run Telegram Bot
        env:
          TELEGRAM_BOT_API: ${{ secrets.TELEGRAM_BOT_API }}  # Token Bot Telegram disimpan di Secrets
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}      # API Key Gemini disimpan di Secrets
        run: |
          python bot.py
