name: Tarna Bot
on:
  schedule:
    - cron: '*/1 * * * *'  # Menjalankan setiap menit, bisa disesuaikan jika perlu
  workflow_dispatch:  # Memungkinkan untuk menjalankan secara manual

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Telegram Bot
        env:
          TELEGRAM_BOT_API: ${{ secrets.TELEGRAM_BOT_API }}  # Pastikan token bot di Secrets
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}      # Pastikan API Key Gemini di Secrets
        run: python bot.py
