name: Telegram Bot Workflow

on:
  schedule:
    - cron: '0 */24 * * *'  # Menjalankan pada menit 0, 32 setiap jam
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    # Konfigurasi concurrency untuk mencegah job duplikat
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false  # Biarkan job sebelumnya selesai

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'  # Caching dependensi untuk instalasi lebih cepat

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run Telegram Bot
        env:
          TELEGRAM_BOT_API: ${{ secrets.TELEGRAM_BOT_API }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python bot.py
